[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
lombok = "1.18.38"
navigationFragment = "2.9.6"
retrofit = "1.9.0"
retrofitVersion = "3.0.0"
converterGson = "3.0.0"
loggingInterceptor = "5.0.0-alpha.16"
dagger = "2.56.2"
daggerCompiler = "2.56.2"
mapstruct = "1.6.3"
mapstructProcessor = "1.6.3"
hiltAndroid = "2.56.2"
lifecycleViewmodel = "2.10.0"
daggerAndroid = "2.56.2"
daggerAndroidProcessor = "2.56.2"
daggerAndroidSupport = "2.56.2"
media3-exoplayer = "1.2.0"
media3-ui = "1.2.0"
media3-exoplayer-hls = "1.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
retrofit = { group = "com.squareup.retrofit", name = "retrofit", version.ref = "retrofit" }
retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "daggerCompiler" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstructProcessor" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "daggerAndroid" }
dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "daggerAndroidProcessor" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "daggerAndroidSupport" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3-exoplayer" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3-ui" }
media3-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3-exoplayer-hls" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

